---
## Ubuntu Handler - main.yml

- name: reload auditd
  service: name=auditd state=reloaded enabled=yes

- name: restart auditd
  service: name=auditd state=restarted enabled=yes

- name: start auditd
  service: name=auditd state=started enabled=yes

- name: stop auditd
  service: name=auditd state=stopped enabled=yes
  

- name: reload fail2ban
  service: name=fail2ban state=reloaded enabled=yes

- name: restart fail2ban
  service: name=fail2ban state=restarted enabled=yes

- name: start fail2ban
  service: name=fail2ban state=started enabled=yes

- name: stop fail2ban
  service: name=fail2ban state=stopped enabled=yes


- name: reload ssh
  service: name=ssh state=reloaded enabled=yes

- name: restart ssh
  service: name=ssh state=restarted enabled=yes

- name: start ssh
  service: name=ssh state=started enabled=yes

- name: stop ssh
  service: name=ssh state=stopped enabled=yes