# cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraMounts:
      - hostPath: /home/ubuntu/certs
        containerPath: /certs
    extraPortMappings:
      - containerPort: 30001
        hostPort: 30001
        listenAddress: "0.0.0.0"
        protocol: TCP
      - containerPort: 30000
        hostPort: 30000
        listenAddress: "0.0.0.0"
        protocol: TCP
      - containerPort: 31000
        hostPort: 31000
        listenAddress: "0.0.0.0"
        protocol: TCP
  - role: worker
    extraMounts:
      - hostPath: /home/ubuntu/certs
        containerPath: /certs
    extraPortMappings:
      - containerPort: 30011
        hostPort: 30011
        listenAddress: "0.0.0.0"
        protocol: TCP
  - role: worker
    extraMounts:
      - hostPath: /home/ubuntu/certs
        containerPath: /certs
    extraPortMappings:
      - containerPort: 30021
        hostPort: 30021
        listenAddress: "0.0.0.0"
        protocol: TCP
  - role: worker
    extraMounts:
      - hostPath: /home/ubuntu/certs
        containerPath: /certs
    extraPortMappings:
      - containerPort: 30031
        hostPort: 30031
        listenAddress: "0.0.0.0"
        protocol: TCP
  - role: worker
    extraMounts:
      - hostPath: /home/ubuntu/certs
        containerPath: /certs
    extraPortMappings:
      - containerPort: 30041
        hostPort: 30041
        listenAddress: "0.0.0.0"
        protocol: TCP