---
- name: Config - AUDIT - Copy audit rules 
  copy:
    src: files/audit/
    dest: /etc/audit/rules.d/
    owner: root
    group: root
    mode: 0640
  notify:
    - restart auditd
  tags:
    - audit
    - config
    - security

- name: Config - FAIL2BAN - Copy jail.j2 file to /etc/fail2ban directory
  template:
    src: jail.j2
    dest: "/etc/fail2ban/jail.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart fail2ban
  tags:
    - config
    - fail2ban
    - security