---

- name: Security - Unattended Upgrades - Copy upgrades.j2 to /etc/apt/apt.conf.d
  template:
    src: upgrades.j2
    dest: "/etc/apt/apt.conf.d/50unattended-upgrades"
    owner: root
    group: root
    mode: 0644
  tags:
    - security
    - upgrades