---
## Ubuntu Role - sysctl.yml

## DIRECTED PINGS
- name: Sysctl - Ignore Directed pings - net.ipv4.icmp_echo_ignore_all - 1
  sysctl:
      name: net.ipv4.icmp_echo_ignore_all
      value: "1"
      sysctl_set: yes
      state: present
      reload: yes
  tags:
    - sysctl
    - security

## ICMP BROADCAST REQUESTS
- name: Sysctl - Ignore ICMP broadcast requests - net.ipv4.icmp_echo_ignore_broadcasts - 0
  sysctl:
      name: net.ipv4.icmp_echo_ignore_broadcasts
      value: "1"
      sysctl_set: yes
      state: present
      reload: yes
  tags:
    - sysctl
    - security

## TOCTOU VULNERABILITIES
- name: Sysctl - Prevent TOCTOU vulnerabilities - fs.protected_hardlinks - 1
  sysctl:
      name: fs.protected_hardlinks
      value: "1"
      sysctl_set: yes
      state: present
      reload: yes
  tags:
    - sysctl
    - security

- name: Sysctl - Prevent TOCTOU vulnerabilities - fs.protected_symlinks - 1
  sysctl:
      name: fs.protected_symlinks
      value: "1"
      sysctl_set: yes
      state: present
      reload: yes
  tags:
    - sysctl
    - security

## IP SPOOFING
- name: Sysctl - IP Spoofing - net.ipv4.conf.all.rp_filter - 1
  sysctl:
      name: net.ipv4.conf.all.rp_filter
      value: "1"
      sysctl_set: yes
      state: present
      reload: yes
  tags:
    - sysctl
    - security

- name: Sysctl - IP Spoofing - net.ipv4.conf.default.rp_filter - 1
  sysctl:
      name: net.ipv4.conf.default.rp_filter
      value: "1"
      sysctl_set: yes
      state: present
      reload: yes
  tags:
    - sysctl
    - security

## SOURCE PACKET ROUTING
- name: Sysctl - Disable source packet routing - net.ipv4.conf.all.accept_source_route - 0
  sysctl:
      name: net.ipv4.conf.all.accept_source_route
      value: "0"
      sysctl_set: yes
      state: present
      reload: yes
  tags:
    - sysctl
    - security

- name: Sysctl - Disable source packet routing - net.ipv6.conf.all.accept_source_route - 0
  sysctl:
      name: net.ipv6.conf.all.accept_source_route
      value: "0"
      sysctl_set: yes
      state: present
      reload: yes
  tags:
    - sysctl
    - security

- name: Sysctl - Disable source packet routing - net.ipv4.conf.default.accept_source_route - 0
  sysctl:
      name: net.ipv4.conf.default.accept_source_route
      value: "0"
      sysctl_set: yes
      state: present
      reload: yes
  tags:
    - sysctl
    - security

- name: Sysctl - Disable source packet routing - net.ipv6.conf.default.accept_source_route - 0
  sysctl:
      name: net.ipv6.conf.default.accept_source_route
      value: "0"
      sysctl_set: yes
      state: present
      reload: yes
  tags:
    - sysctl
    - security

## SEND REDIRECTS
- name: Sysctl - Ignore send redirects - net.ipv4.conf.all.send_redirects - 0
  sysctl:
      name: net.ipv4.conf.all.send_redirects
      value: "0"
      sysctl_set: yes
      state: present
      reload: yes
  tags:
    - sysctl
    - security

- name: Sysctl - Ignore send redirects - net.ipv4.conf.default.send_redirects - 0
  sysctl:
      name: net.ipv4.conf.default.send_redirects
      value: "0"
      sysctl_set: yes
      state: present
      reload: yes
  tags:
    - sysctl
    - security

## SYN ATTACKS
- name: Sysctl - Block SYN attacks - net.ipv4.tcp_syncookies - 1
  sysctl:
      name: net.ipv4.tcp_syncookies
      value: "1"
      sysctl_set: yes
      state: present
      reload: yes
  tags:
    - sysctl
    - security

- name: Sysctl - Block SYN attacks - net.ipv4.tcp_synack_retries - 2
  sysctl:
      name: net.ipv4.tcp_synack_retries
      value: "2"
      sysctl_set: yes
      state: present
      reload: yes
  tags:
    - sysctl
    - security

- name: Sysctl - Block SYN attacks - net.ipv4.tcp_syn_retries - 5
  sysctl:
      name: net.ipv4.tcp_syn_retries
      value: "5"
      sysctl_set: yes
      state: present
      reload: yes
  tags:
    - sysctl
    - security

## LOG MARTIANS
- name: Sysctl - Log Martians - net.ipv4.conf.all.log_martians - 1
  sysctl:
      name: net.ipv4.conf.all.log_martians
      value: "1"
      sysctl_set: yes
      state: present
      reload: yes
  tags:
    - sysctl
    - security

- name: Sysctl - Log Martians - net.ipv4.icmp_ignore_bogus_error_responses - 1
  sysctl:
      name: net.ipv4.icmp_ignore_bogus_error_responses
      value: "1"
      sysctl_set: yes
      state: present
      reload: yes
  tags:
    - sysctl
    - security

## ICMP REDIRECTS
- name: Sysctl - Ignore ICMP redirects - net.ipv4.conf.all.accept_redirects - 0
  sysctl:
      name: net.ipv4.conf.all.accept_redirects
      value: "0"
      sysctl_set: yes
      state: present
      reload: yes
  tags:
    - sysctl
    - security

- name: Sysctl - Ignore ICMP redirects - net.ipv6.conf.all.accept_redirects - 0
  sysctl:
      name: net.ipv6.conf.all.accept_redirects
      value: "0"
      sysctl_set: yes
      state: present
      reload: yes
  tags:
    - sysctl
    - security

- name: Sysctl - Ignore ICMP redirects - net.ipv4.conf.default.accept_redirects - 0
  sysctl:
      name: net.ipv4.conf.default.accept_redirects
      value: "0"
      sysctl_set: yes
      state: present
      reload: yes
  tags:
    - sysctl
    - security

- name: Sysctl - Ignore ICMP redirects - net.ipv6.conf.default.accept_redirects - 0
  sysctl:
      name: net.ipv6.conf.default.accept_redirects
      value: "0"
      sysctl_set: yes
      state: present
      reload: yes
  tags:
    - sysctl
    - security

## THROUGHPUT CONFIGURATIONS
### FS
- name: Sysctl - Throughput - fs.file-max - 65535
  sysctl:
      name: fs.file-max
      value: "65535"
      sysctl_set: yes
      state: present
      reload: yes
  tags:
    - sysctl
    - security

### KERNEL
- name: Sysctl - Throughput - kernel.pid_max - 65535
  sysctl:
      name: kernel.pid_max
      value: "65535"
      sysctl_set: yes
      state: present
      reload: yes
  tags:
    - sysctl
    - security

### CORE
- name: Sysctl - Throughput - net.core.netdev_max_backlog - 16384
  sysctl:
      name: net.core.netdev_max_backlog
      value: "16384"
      sysctl_set: yes
      state: present
      reload: yes
  tags:
    - sysctl
    - security

- name: Sysctl - Throughput - net.core.rmem_max - 33554432
  sysctl:
      name: net.core.rmem_max
      value: "33554432"
      sysctl_set: yes
      state: present
      reload: yes
  tags:
    - sysctl
    - security

- name: Sysctl - Throughput - net.core.wmem_max - 33554432
  sysctl:
      name: net.core.wmem_max
      value: "33554432"
      sysctl_set: yes
      state: present
      reload: yes
  tags:
    - sysctl
    - security

- name: Sysctl - Throughput - net.core.somaxconn - 16384
  sysctl:
      name: net.core.somaxconn
      value: "16384"
      sysctl_set: yes
      state: present
      reload: yes
  tags:
    - sysctl
    - security

### IPV4
- name: Sysctl - Throughput - net.ipv4.tcp_fin_timeout - 15
  sysctl:
      name: net.ipv4.tcp_fin_timeout
      value: "15"
      sysctl_set: yes
      state: present
      reload: yes
  tags:
    - sysctl
    - security

- name: Sysctl - Throughput - net.ipv4.tcp_keepalive_intvl - 10
  sysctl:
      name: net.ipv4.tcp_keepalive_intvl
      value: "10"
      sysctl_set: yes
      state: present
      reload: yes
  tags:
    - sysctl
    - security

- name: Sysctl - Throughput - net.ipv4.tcp_keepalive_probes - 4
  sysctl:
      name: net.ipv4.tcp_keepalive_probes
      value: "4"
      sysctl_set: yes
      state: present
      reload: yes
  tags:
    - sysctl
    - security

- name: Sysctl - Throughput - net.ipv4.tcp_keepalive_time - 30
  sysctl:
      name: net.ipv4.tcp_keepalive_time
      value: "30"
      sysctl_set: yes
      state: present
      reload: yes
  tags:
    - sysctl
    - security

- name: Sysctl - Throughput - net.ipv4.tcp_max_syn_backlog - 65536
  sysctl:
      name: net.ipv4.tcp_max_syn_backlog
      value: "65536"
      sysctl_set: yes
      state: present
      reload: yes
  tags:
    - sysctl
    - security

- name: Sysctl - Throughput - net.ipv4.tcp_max_tw_buckets - 400000
  sysctl:
      name: net.ipv4.tcp_max_tw_buckets
      value: "400000"
      sysctl_set: yes
      state: present
      reload: yes
  tags:
    - sysctl
    - security

- name: Sysctl - Throughput - net.ipv4.tcp_rmem - 4096 87380 33554432
  sysctl:
      name: net.ipv4.tcp_rmem
      value: "4096 87380 33554432"
      sysctl_set: yes
      state: present
      reload: yes
  tags:
    - sysctl
    - security

- name: Sysctl - Throughput - net.ipv4.tcp_sack - 1
  sysctl:
      name: net.ipv4.tcp_sack
      value: "1"
      sysctl_set: yes
      state: present
      reload: yes
  tags:
    - sysctl
    - security

- name: Sysctl - Throughput - net.ipv4.tcp_slow_start_after_idle - 0
  sysctl:
      name: net.ipv4.tcp_slow_start_after_idle
      value: "0"
      sysctl_set: yes
      state: present
      reload: yes
  tags:
    - sysctl
    - security

- name: Sysctl - Throughput - net.ipv4.tcp_timestamps - 1
  sysctl:
      name: net.ipv4.tcp_timestamps
      value: "1"
      sysctl_set: yes
      state: present
      reload: yes
  tags:
    - sysctl
    - security

- name: Sysctl - Throughput - net.ipv4.tcp_wmem - 4096 65536 33554432
  sysctl:
      name: net.ipv4.tcp_wmem
      value: "4096 65536 33554432"
      sysctl_set: yes
      state: present
      reload: yes
  tags:
    - sysctl
    - security

- name: Sysctl - Throughput - net.ipv4.tcp_window_scaling - 1
  sysctl:
      name: net.ipv4.tcp_window_scaling
      value: "1"
      sysctl_set: yes
      state: present
      reload: yes
  tags:
    - sysctl
    - security

### VM
- name: Sysctl - Throughput - vm.max_map_count - 262144
  sysctl:
      name: vm.max_map_count
      value: "262144"
      sysctl_set: yes
      state: present
      reload: yes
  tags:
    - sysctl
    - security

- name: Sysctl - Throughput - vm.swappiness - 0
  sysctl:
      name: vm.swappiness
      value: "0"
      sysctl_set: yes
      state: present
      reload: yes
  tags:
    - sysctl
    - security