- name: Create /mnt/data
  ansible.builtin.file:
    path: /mnt/data
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0777'
  tags: minio

- name: Download minio server native binary
  ansible.builtin.get_url:
    url: https://dl.min.io/server/minio/release/linux-amd64/minio
    dest: /usr/local/bin
    mode: '0777'
  tags: minio

- name: Download minio client native binary
  ansible.builtin.get_url:
    url: https://dl.min.io/client/mc/release/linux-amd64/mc
    dest: /usr/local/bin
    mode: '0777'
  tags: minio

- name: create tools dir
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0775
  loop:
    - /home/{{ user }}/minio/tools/deploy/docker/docker-compose/
    - /home/{{ user }}/minio/tools/deploy/docker/docker-cli/
    - /home/{{ user }}/minio/tools/deploy/native/
    - /home/{{ user }}/minio/tools/deploy/mc/
    - /home/{{ user }}/minio/tools/deploy/k8s/operator/
  tags: minio

## MC Client Setup
- name: Copy minio mc client setup script
  ansible.builtin.copy:
    src: ../../files/{{ deployment_name }}/minio-client-setup.sh
    dest: "/home/{{ user }}/minio/tools/deploy/mc/minio-client-setup.sh"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755
    force: yes
  tags: minio

- name: Copy minio mc site repl script
  ansible.builtin.copy:
    src: ../../files/{{ deployment_name }}/minio-site-repl-setup.sh
    dest: "/home/{{ user }}/minio/tools/deploy/mc/minio-site-repl-setup.sh"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755
    force: yes
  tags: minio

#Minio Docker Setup
- name: Copy minio docker-compose file
  template:
    src: "docker-compose.yml.j2"
    dest: "/home/{{ user }}/minio/tools/deploy/docker/docker-compose/docker-compose.yml"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755
  tags: minio

- name: Copy nginx.conf
  ansible.builtin.copy:
    src: files/docker/nginx.conf
    dest: "/home/{{ user }}/minio/tools/deploy/docker/docker-compose/nginx.conf"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755
    force: yes
  tags: minio

- name: Copy start docker-compose script
  template:
    src: "minio-docker-compose-start.sh.j2"
    dest: "/home/{{ user }}/minio/tools/deploy/docker/docker-compose/minio-docker-compose-start.sh"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755
  tags: minio

- name: Copy stop docker-compose script
  template:
    src: "minio-docker-compose-stop.sh.j2"
    dest: "/home/{{ user }}/minio/tools/deploy/docker/docker-compose/minio-docker-compose-stop.sh"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755
  tags: minio

#Minio Systemd Local Setup
- name: Copy minio systemd file
  template:
    src: "minio-systemd.j2"
    dest: "/etc/systemd/system/minio.service"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755
  tags: minio

- name: Copy minio systemd file example
  template:
    src: "minio-systemd.j2"
    dest: "/home/{{ user }}/minio/tools/deploy/native/minio.service.example"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755
  tags: minio

- name: Copy minio systemd config file
  template:
    src: "minio-config.j2"
    dest: "/etc/default/minio"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755
  tags: minio

- name: Copy minio systemd config file example
  template:
    src: "minio-config.j2"
    dest: "/home/{{ user }}/minio/tools/deploy/native/minio-config.example"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755
  tags: minio

- name: copy contents of native dir to remote host
  ansible.builtin.copy:
    src: files/native/
    dest: /home/{{ user }}/minio/tools/deploy/native/
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755
    directory_mode:
  tags: minio

- name: Copy minio native start all script
  ansible.builtin.copy:
    src: ../../files/{{ deployment_name }}/minio-native-start-all.sh
    dest: "/home/{{ user }}/minio/tools/deploy/native/minio-native-start-all.sh"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755
    force: yes
  tags: minio